controller_manager:
  ros__parameters:
    update_rate: 1

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pos_group:
      type: position_controllers/JointGroupPositionController

pos_group:
  ros__parameters:
    joints: [hip, knee]
